import { logger } from '@/lib/logger';
import { Platform } from 'react-native';

/**
 * Rich Notification service (Phase 15 — "Alive" driver-en-route notification).
 *
 * Wraps @notifee/react-native to post and SILENTLY UPDATE a single notification
 * (keyed by tripId) as the driver approaches:
 *   • a live countdown chronometer ("Driver arriving in 4 mins" that ticks down)
 *   • a Static-Maps route snapshot as the expanded big-picture / iOS attachment
 *
 * The update is driven by `trip:eta-update` socket events (foreground). Reusing
 * the same notification `id` + `onlyAlertOnce` means each refresh replaces the
 * tray entry in place with no new sound/buzz.
 *
 * GRACEFUL DEGRADATION: notifee is a native module — it has no web build and
 * isn't available in Expo Go. Every function lazy-requires it and no-ops when
 * unavailable, so the app keeps working everywhere; the rich notification only
 * appears in a development/EAS build on a device.
 */

const CHANNEL_ID = 'ride-eta';

// Lazy require so importing this module never crashes web / Expo Go.
type NotifeeModule = typeof import('@notifee/react-native');
let _notifee: NotifeeModule | null = null;

function getNotifee(): NotifeeModule | null {
  if (Platform.OS === 'web') return null;
  if (_notifee) return _notifee;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    _notifee = require('@notifee/react-native');
    return _notifee;
  } catch {
    logger.debug('[RichNotif] notifee unavailable (Expo Go?) — skipping rich notifications.');
    return null;
  }
}

let channelReady = false;
async function ensureChannel(n: NotifeeModule): Promise<void> {
  if (channelReady || Platform.OS !== 'android') {
    channelReady = true;
    return;
  }
  await n.default.createChannel({
    id: CHANNEL_ID,
    name: 'Ride Updates',
    importance: n.AndroidImportance.HIGH,
  });
  channelReady = true;
}

export interface DriverEnRouteParams {
  tripId: string;
  /** Whole minutes until the driver reaches the pickup. */
  etaMin: number;
  /** Static-Maps route snapshot URL (optional). */
  routeImageUrl?: string | null;
}

/**
 * Post (or silently update) the rider's "driver on the way" notification.
 * Safe to call repeatedly with the same tripId — it replaces the tray entry.
 */
export async function displayDriverEnRoute({
  tripId,
  etaMin,
  routeImageUrl,
}: DriverEnRouteParams): Promise<void> {
  const n = getNotifee();
  if (!n) return;

  try {
    await ensureChannel(n);
    const minutes = Math.max(1, Math.round(etaMin));

    await n.default.displayNotification({
      id: tripId, // stable id → updates replace, never stack
      title: `Driver arriving in ${minutes} min${minutes === 1 ? '' : 's'}`,
      body: 'Your driver is on the way 🚗',
      android: {
        channelId: CHANNEL_ID,
        // Dedicated monochrome notification icon generated by the
        // expo-notifications config plugin (./assets/images/android-icon-monochrome.png).
        smallIcon: 'notification_icon',
        color: '#2563EB',
        onlyAlertOnce: true, // subsequent refreshes are silent (no buzz)
        ongoing: true, // sticky while the trip is live
        // Live countdown timer in the tray (ticks toward the ETA).
        showChronometer: true,
        chronometerDirection: 'down',
        timestamp: Date.now() + minutes * 60 * 1000,
        pressAction: { id: 'default' },
        ...(routeImageUrl
          ? { style: { type: n.AndroidStyle.BIGPICTURE, picture: routeImageUrl } }
          : {}),
      },
      ios: {
        ...(routeImageUrl
          ? { attachments: [{ url: routeImageUrl }] }
          : {}),
      },
    });
  } catch (e) {
    logger.debug('[RichNotif] displayDriverEnRoute failed:', (e as Error).message);
  }
}

/** Clear the driver-en-route notification (call on ARRIVED / COMPLETED / cancel). */
export async function cancelDriverEnRoute(tripId: string): Promise<void> {
  const n = getNotifee();
  if (!n) return;
  try {
    await n.default.cancelNotification(tripId);
  } catch {
    /* ignore */
  }
}

/**
 * Register the background event handler (taps/dismiss while backgrounded/quit).
 * Must run once at JS load, OUTSIDE the React tree — call from the app entry.
 *
 * NOTE: notifee handles notification *interactions* in the background, but not
 * receiving remote messages. True server-pushed updates while the app is
 * backgrounded require an FCM data-message handler (see PROJECT_STATE Phase 15).
 */
export function registerNotifeeBackgroundHandler(): void {
  const n = getNotifee();
  if (!n) return;
  try {
    n.default.onBackgroundEvent(async ({ type, detail }) => {
      // Tapping the notification opens the app; routing is handled by the
      // existing pushService tap listeners in the root layout.
      if (type === n.EventType.PRESS) {
        // no-op: cold/warm routing handled elsewhere
      }
      void detail;
    });
  } catch (e) {
    logger.debug('[RichNotif] background handler registration skipped:', (e as Error).message);
  }
}
